name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "31 7 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
      - name: Commit & Push
        run: |
          git config user.name ${{ github.repository_owner }}
          git config user.email o0frego0o@hotmail.com
          git add -A .
          git commit -m "GitHub 3D Profile"
          git push
